services:
  - type: web
    name: insurance-claim-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_DB_URL
        value: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SUPABASE_DB_USERNAME
        value: postgres.evsmqptouoayfdhceagy
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: insuranceclmvrfctn@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
      - key: BOOTSTRAP_ADMIN_NAME
        value: Admin
      - key: BOOTSTRAP_ADMIN_EMAIL
        value: insuranceclmvrfctn@gmail.com
